# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - iot-configmap.yaml
  - iot-deployment.yaml
  - iot-service.yaml
  - iot-ingress.yaml

# usage: kubectl apply -k