global:
  edition: ce
  hosts:
    domain: cadet.in.th
    hostSuffix: ""
    gitlab:
      name: gitlab.cadet.in.th
      https: true

  gatewayApi:
    enabled: false
    installEnvoy: false
    configureCertmanager: false

  kas:
    enabled: false

  # --------------------------------------------------
  # 1. เชื่อมต่อ External PostgreSQL
  # --------------------------------------------------
  psql:
    host: postgresql.gitlab.svc.cluster.local
    port: 5432
    database: gitlabhq_production
    username: gitlab

  # --------------------------------------------------
  # 2. เชื่อมต่อ External Redis
  # --------------------------------------------------
  redis:
    host: gitlab-redis-master.gitlab.svc.cluster.local
    port: 6379


  # --------------------------------------------------
  # 3. เชื่อมต่อ External MinIO (S3 Object Storage)
  # --------------------------------------------------
  appConfig:
    object_store:
      enabled: true

# docker image registry
registry:
  enabled: false

# --------------------------------------------------
# ปิด Services ที่ยังไม่จำเป็นสำหรับ Push / Minimal Code Host
# --------------------------------------------------
gitlab-runner:
  install: false          # ไม่รัน CI

prometheus:
  install: false          # ปิด Monitoring

installCertmanager: false

certmanager:
  installCRDs: false

certmanager-issuer:
  email: email@example.com

gatewayApi:
  enable: false

gitlab:
  gitaly:
    persistence:
      enabled: true
      storageClass: "gitlab-pv"
      size: 50Gi