secrets:
   accessKey: "access-key"
   secretKey: "secret-key"

objectStore:
   name: primary-object-store
   pools:
   - name: pool-0
     servers: 1
     volumesPerServer: 1
     size: 2Gi
     storageClassName: minio-pv
   services:
      minio:
         serviceType: NodePort
         nodePort: 31000