Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-24.04"
    config.vm.define "pnamnilS" do |pnamnilS|
        pnamnilS.vm.hostname = "pnamnilS"
        pnamnilS.vm.network "private_network", ip: "192.168.56.110"
        pnamnilS.vm.provider "virtualbox" do |vb|
            vb.cpus = "2"
            vb.memory = "2048"
        end
        pnamnilS.vm.synced_folder "./confs", "/mnt/confs", create:true
        pnamnilS.vm.provision "shell", path: "scripts/server.sh"
    end
end
