Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-24.04"

    config.vm.define "pnamnilS" do |pnamnilS|
        pnamnilS.vm.hostname = "pnamnilS"
        pnamnilS.vm.network "private_network", ip: "192.168.56.110"
        pnamnilS.vm.provider "virtualbox" do |vb|
            vb.cpus = "2"
            vb.memory = "2048"
        end
        pnamnilS.vm.synced_folder "./confs", "/home/vagrant/confs", create:true

        pnamnilS.vm.provision "shell", path: "./scripts/server.sh"
    end

    config.vm.define "pnamnilSW" do |pnamnilSW|
        pnamnilSW.vm.hostname = "pnamnilSW"
        pnamnilSW.vm.network "private_network", ip: "192.168.56.111"
        pnamnilSW.vm.provider "virtualbox" do |vb|
            vb.cpus = "1"
            vb.memory = "1024"
        end
        pnamnilSW.vm.synced_folder "./confs", "/home/vagrant/confs", create:true
        pnamnilSW.vm.provision "shell", path: "./scripts/worker.sh"
    end
end
