apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongodb
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=

---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
  namespace: mongodb
type: Opaque
data:
  mongo-auth-username: dXNlcm5hbWU=
  mongo-auth-password: cGFzc3dvcmQ=

---
