apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: gitlab
data:
  postgres-password: something-secret
  password: something-secret

---

# apiVersion: v1
# kind: Secret
# metadata:
#   name: gitlab-minio-secret
#   namespace: gitlab
# data:
#   rootUser: something-secret
#   rootPassword : something-secret
