global:
  edition: ce
  hosts:
    domain: cadet.in.th
    hostSuffix: ""
    gitlab:
      name: gitlab.cadet.in.th
      https: true

  gatewayApi:
    enabled: false
    installEnvoy: false

  # --------------------------------------------------
  # 1. เชื่อมต่อ External PostgreSQL
  # --------------------------------------------------
  psql:
    host: postgresql.gitlab.svc.cluster.local
    port: 5432
    database: gitlabhq_production
    username: gitlab
    # password:
    #   secret: cadet-secret
    #   key: password

  # --------------------------------------------------
  # 2. เชื่อมต่อ External Redis
  # --------------------------------------------------
  redis:
    host: gitlab-redis-master.gitlab.svc.cluster.local
    port: 6379
    # password:
    #   secret: cadet-secret
    #   key: secret


  # --------------------------------------------------
  # 3. เชื่อมต่อ External MinIO (S3 Object Storage)
  # --------------------------------------------------
  appConfig:
    object_store:
      enabled: true
      # connection:
      #   secret: gitlab-s3-connection
      #   key: connection
registry:
  enabled: false
    # lfs:
    #   connection:
    #     secret: gitlab-s3-connection
    #     key: connection
    # artifacts:
    #   connection:
    #     secret: gitlab-s3-connection
    #     key: connection
    # uploads:
    #   connection:
    #     secret: gitlab-s3-connection
    #     key: connection
    # packages:
    #   connection:
    #     secret: gitlab-s3-connection
    #     key: connection

  # ปิด Ingress controller ของ GitLab เอง (เราใช้ Traefik อยู่แล้ว)
  # ingress:
  #   configureCertmanager: false
  #   enabled: false

# --------------------------------------------------
# ปิด Services ภายในคลัสเตอร์ที่เรามีตัวแยกอยู่แล้ว
# --------------------------------------------------
# postgresql:
#   install: false

# redis:
#   install: false

# minio:
#   install: false

# --------------------------------------------------
# ปิด Services ที่ยังไม่จำเป็นสำหรับ Push / Minimal Code Host
# --------------------------------------------------
gitlab-runner:
  install: false          # ไม่รัน CI

prometheus:
  install: false          # ปิด Monitoring

installCertmanager: false

certmanager:
  installCRDs: false

certmanager-issuer:
  email: email@example.com

gatewayApi:
  enable: false

# certmanager:
#   install: false          # ไม่ใช้ cert-manager

# nginx-ingress:
#   enabled: false          # ไม่ลง Nginx ซ้อนกับ Traefik